'use strict';
/** サンプル案件6件（プロト/ GAS 版から移植）。空DB時のみ投入。 */
function sampleCases(defaultConfirm) {
  const stamp = d => d + 'T00:00:00';
  const cases = [
    { id: 'c1', type: 'LW', status: '完了', koban: 'LW25004', motoKoban: 'LW24310', nohinNo: 'D-1180', kobanName: 'ブートップボックス 搬出', nohinSaki: '住友建機株式会社', okyakuSub: '稲毛事業所 関', basho: '千葉県千葉市稲毛区', tantou: '関', tel: '043-000-0000', kishu: 'LN-2400', katashiki: 'BT-2400S', seiban: '24-1180', nenGappi: '2024-08', yoteibi: '2026-05-30', shijiNaiyou: 'ブートップボックス搬出。台車整備と動作確認。', workTypes: { '納品': true }, paid: '有償', genin: 'ブートップボックス搬出に伴う台車整備。', shori: '台車の整備を行い、動作確認を実施。下降レベルを確認。', confirmItems: [{ key: 'brake', label: 'ブレーキ調整スイッチOFF', value: '✓' }, { key: 'rbpos', label: 'R/B+POSの作業原点復帰', value: '✓' }, { key: 'force', label: '強制運転時からの復帰', value: '−' }], staff: [{ id: 's1', name: '今泉', separate: false }], commonWork: [{ date: '2026-05-30', start: '09:00', end: '12:15' }], commonTravel: [{ dir: '往路', date: '2026-05-30', start: '07:30', end: '09:00', km: '45' }], oshaName: '住友建機株式会社', tantoushaName: '関', kanin: { stamped: true, name: '製造部 田中' } },
    { id: 'c2', type: 'LW', status: '作業中', koban: 'LW25083', motoKoban: 'LW25010', nohinNo: 'D-1205', kobanName: '3m切断走行 据付', nohinSaki: '三星重工業', okyakuSub: '名古屋工場 高木', basho: '愛知県名古屋市港区', tantou: '高木 信治', tel: '052-000-0000', kishu: 'LN-3000', katashiki: 'CT-3000', seiban: '25-0083', nenGappi: '2025-03', yoteibi: '2026-06-02', shijiNaiyou: '3m切断走行の据付・メンテ説明および動作確認。', workTypes: { '据付': true }, paid: '有償', genin: '3m切断走行の据付。', shori: '据付・メンテ説明および動作確認を実施。ねじM20×80→M20×110に変更、20mm上げた。', confirmItems: [{ key: 'brake', label: 'ブレーキ調整スイッチOFF', value: '✓' }, { key: 'rbpos', label: 'R/B+POSの作業原点復帰', value: '−' }, { key: 'force', label: '強制運転時からの復帰', value: '✓' }], staff: [{ id: 's1', name: '高木 信治', separate: false }, { id: 's2', name: '山田 太郎', separate: false }, { id: 's3', name: '佐藤 健', separate: true, work: [{ date: '2026-06-02', start: '13:00', end: '18:00' }], travel: [{ dir: '往路', date: '2026-06-02', start: '11:00', end: '13:00', km: '90' }] }], commonWork: [{ date: '2026-06-02', start: '09:00', end: '17:00' }], commonTravel: [{ dir: '往路', date: '2026-06-02', start: '06:00', end: '09:00', km: '180' }], oshaName: '三星重工業', tantoushaName: '高木 信治', kanin: { stamped: false, name: '製造部 田中' } },
    { id: 'c3', type: 'TS', status: '未着手', koban: 'TS26008', motoKoban: '', nohinNo: '', kobanName: '定期点検 作業', nohinSaki: '北陸テクノ工業', okyakuSub: '', basho: '石川県金沢市', tantou: '橋部', tel: '076-000-0000', kishu: 'NEMAN-L', katashiki: 'L-NEMAN', seiban: 'TS-26008', nenGappi: '2022-05', yoteibi: '2026-06-06', shijiNaiyou: '定期点検作業。前後軸・モータ減速機の型式確認。', workTypes: { '点検': true }, paid: '有償', genin: '', shori: '', confirmItems: defaultConfirm('TS'), staff: [{ id: 's1', name: '', separate: false }], commonWork: [{ date: '2026-06-06', start: '', end: '' }], commonTravel: [{ dir: '往路', date: '', start: '', end: '', km: '' }], oshaName: '北陸テクノ工業', tantoushaName: '橋部', kanin: { stamped: false, name: 'TSC 木下' } },
    { id: 'c4', type: 'TS', status: '未着手', koban: 'TS26052', motoKoban: '', nohinNo: '', kobanName: '油圧引交換・簡易点検', nohinSaki: '株式会社 赤木鉄工所', okyakuSub: '', basho: '宮崎県東諸県郡国富町', tantou: '赤木', tel: '0985-00-0000', kishu: 'AK-1200', katashiki: 'AK-1200H', seiban: 'TS-26052', nenGappi: '2021-11', yoteibi: '2026-06-16', shijiNaiyou: '油圧引交換、簡易点検。回転軸部の溶接状態確認。', workTypes: { '修理': true }, paid: '有償', genin: '', shori: '', confirmItems: defaultConfirm('TS'), staff: [{ id: 's1', name: '', separate: false }], commonWork: [{ date: '2026-06-16', start: '', end: '' }], commonTravel: [{ dir: '往路', date: '', start: '', end: '', km: '' }], oshaName: '株式会社 赤木鉄工所', tantoushaName: '赤木', kanin: { stamped: false, name: 'TSC 木下' } },
    { id: 'c5', type: 'LW', status: '作業中', koban: 'LW25120', motoKoban: 'LW25040', nohinNo: 'D-1260', kobanName: '大型ライン 据付（5日間）', nohinSaki: '大手重工業株式会社', okyakuSub: '若松製造所 松本', basho: '福岡県北九州市若松区', tantou: '松本 浩一', tel: '093-000-0000', kishu: 'LN-5000', katashiki: 'CT-5000W', seiban: '25-0120', nenGappi: '2025-04', yoteibi: '2026-06-09', shijiNaiyou: '大型切断ラインの据付。往復とも片道1日移動、現地5日間。', workTypes: { '据付': true }, paid: '有償', genin: '新規ライン導入に伴う据付。', shori: '本体据付・芯出し・配線・試運転・メンテ説明まで実施。動作確認良好。', confirmItems: [{ key: 'brake', label: 'ブレーキ調整スイッチOFF', value: '✓' }, { key: 'rbpos', label: 'R/B+POSの作業原点復帰', value: '✓' }, { key: 'force', label: '強制運転時からの復帰', value: '✓' }], staff: [{ id: 's1', name: '高木 信治', separate: false }, { id: 's2', name: '山田 太郎', separate: false }], commonWork: [{ date: '2026-06-09', start: '08:30', end: '17:30' }, { date: '2026-06-10', start: '08:00', end: '18:00' }, { date: '2026-06-11', start: '08:00', end: '18:30' }, { date: '2026-06-12', start: '08:00', end: '17:00' }, { date: '2026-06-13', start: '08:30', end: '15:00' }], commonTravel: [{ dir: '往路', date: '2026-06-08', start: '07:00', end: '19:00', km: '480' }, { dir: '復路', date: '2026-06-14', start: '07:00', end: '19:00', km: '480' }], oshaName: '大手重工業株式会社', tantoushaName: '松本 浩一', kanin: { stamped: false, name: '製造部 田中' } },
    { id: 'c6', type: 'LW', status: '作業中', koban: 'LW25200', motoKoban: 'LW25090', nohinNo: 'D-1320', kobanName: '長文テスト（原因・処理が長い場合）', nohinSaki: 'テスト製作所株式会社', okyakuSub: '第一工場 検証 太郎', basho: '東京都大田区テスト町1-2-3', tantou: '検証 太郎', tel: '03-0000-0000', kishu: 'TEST-9000', katashiki: 'TST-9000L', seiban: '25-0200', nenGappi: '2025-06', yoteibi: '2026-06-20', shijiNaiyou: '長文表示の検証用サンプル。原因・処理ともに非常に長い本文を入力した場合のPDFレイアウトを確認するためのデータです。', workTypes: { '修理': true, '点検': true }, paid: '有償', genin: '【原因】本サンプルは長文表示の確認用です。装置の稼働中に断続的な異音および振動が発生し、稼働開始からおよそ三十分が経過した時点で安全装置が作動して停止する事象が複数回確認されました。点検の結果、主軸まわりの軸受に経年劣化による微細な摩耗が認められ、潤滑状態の不良とあわせて振動増大の主因と推定されます。', shori: '【処理】軸受を新品へ交換し、主軸の芯出しおよび回転バランスの再調整を実施しました。交換・調整後に連続運転試験を二時間実施し、異音・振動・温度上昇のいずれも基準値内であること、安全装置の不要作動が発生しないことを確認しています。最後にお客様立会いのもと動作確認を行い、正常稼働を確認のうえ作業を完了しました。', confirmItems: [{ key: 'brake', label: 'ブレーキ調整スイッチOFF', value: '✓' }, { key: 'rbpos', label: 'R/B+POSの作業原点復帰', value: '✓' }, { key: 'force', label: '強制運転時からの復帰', value: '−' }], staff: [{ id: 's1', name: '検証 太郎', separate: false }], commonWork: [{ date: '2026-06-20', start: '09:00', end: '17:30' }], commonTravel: [{ dir: '往路', date: '2026-06-20', start: '07:30', end: '09:00', km: '40' }, { dir: '復路', date: '2026-06-20', start: '17:30', end: '19:00', km: '40' }], oshaName: 'テスト製作所株式会社', tantoushaName: '検証 太郎', kanin: { stamped: false, name: '製造部 田中' } }
  ];
  cases.forEach(c => {
    c.signature = ''; c.signatureFileId = ''; c.pdfFileId = ''; c.driveFolderId = '';
    c.archived = false; c.closedAt = '';
    c.createdAt = stamp(c.yoteibi); c.updatedAt = stamp(c.yoteibi);
  });
  return cases;
}
module.exports = { sampleCases };
